name: Build MSI Release

on: 
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish App
        run: >
          dotnet publish GUI/GUI.csproj
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=false
          -o publish

      - name: Copy icon to installer folder
        run: copy GUI\Assets\icon.ico installer\icon.ico

      - name: Install WiX
        run: dotnet tool install --global wix

      - name: Build MSI
        run: |
          wix build installer/Product.wxs `
            -acceptEula wix7 `
            -define PublishDir="$(pwd)\publish" `
            -out NetYtDownloader.msi
        env:
          WIX_ACCEPT_LICENSE: yes

      - name: Generate update.json
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".TrimStart("v")
          $repo = "${{ github.repository }}"
          $tag = "${{ github.ref_name }}"
          $url = "https://github.com/$repo/releases/download/$tag/NetYtDownloader.msi"

          $json = @{
            version = $version
            url = $url
          } | ConvertTo-Json -Depth 3

          $json | Out-File -FilePath update.json -Encoding utf8

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: | 
            NetYtDownloader.msi
            update.json